
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 9443
      nodePort: 30007
  selector:
    control-plane: controller-manager
